module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.spec.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  testTimeout: 20000,
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  testPathIgnorePatterns: [],
  collectCoverage: true,
  coveragePathIgnorePatterns: [],
  collectCoverageFrom: [
    '**/*.{ts,tsx}',
    '!**/node_modules/**',
    '!**/interfaces/**',
    '!**/mock/**',
    '!**/commom/**',
    '!**/migrations*/**',
    '!**/enum/**',
    '!**/index.ts',
    '!**/*.module.ts',
    '!**/*.entity.**',
    '!**/*.dto.**',
    '!envs.ts',
    '!**/*.controller.**',
    '!<rootDir>/main.ts',
    '!<rootDir>/*.config.ts',
    '!<rootDir>/ormconfig.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 95,
      functions: 95,
      lines: 95,
      statements: 95,
    },
  },
  coverageReporters: ['json', 'html', 'text'],
  preset: 'ts-jest',
};
